### ISSUE TITLE
Maybe the plugin should not transform the data coming from Prinful API

### ISSUE THREAD

**Issue by svengau** [ynnoj/gatsby-source-printful#12]
Hi @ynnoj, and thanks increasing the page limit.

I've met 2 new issues when using this plugin: 
1/ the prices are multiple by 100. I know Stripe uses cents, but not Paypal. I think the plugin should not change the pricing values and let the dev handle them. 
2/ variant ID is overridden by external ID. This one is a bit more annoying, because we need the variant Id to create the order (or retrieve the variant using the API).

What do you think ?

**Comment by ynnoj** [comment]
@svengau Thanks for the feedback! Can you create separate issues for each? Happy to resolve 2 right away. 1 is a breaking change.
