### ISSUE TITLE
why prices are multiple by 100 ?

### ISSUE THREAD

**Issue by svengau** [ynnoj/gatsby-source-printful#14]
Hi @ynnoj, 

All prices are multiple by 100 with this plugin. I know Stripe uses cents, but not Paypal. And thus when we create orders using the official Printful API, we have to divide prices by 100.

I think the plugin should not change the pricing values and let the dev handle them.

What do you think ?

**Comment by ynnoj** [comment]
@svengau Would your preference be for the node fields to return the formatted price string from Printful?

**Comment by svengau** [comment]
Printful API sends back a string, it could be interested to have directly a Float.

**Comment by ynnoj** [comment]
@svengau Happy to accept a PR that adds a new raw field to prevent any breaking changes.

**Comment by svengau** [comment]
@ynnoj I propose you this PR. I haven't found an elegant way to include a 2nd raw field, without making this plugin difficult to understand at first glance. I think two fields, like "detail_price" and "raw_price", will just confuse your users.
This project only has a few users, so I think it's a good time to fix things before having more. 

Last but not least, there is another bug hidden behind it. You use parseInt instead of parseFloat, so you already get rid of the cents.
https://github.com/ynnoj/gatsby-source-printful/blob/2585e522c09ae944563b8423ea03ae760efe86c4/gatsby-source-printful/lib/utils.js#L5

**Comment by ynnoj** [comment]
> Last but not least, there is another bug hidden behind it. You use parseInt instead of parseFloat, so you already get rid of the cents.

@svengau Yeah, that was probably an oversight of mine when working with Stripe 😅

**Comment by LuigiClaudio** [comment]
Just noticed it. I have `retail_price: 44.95` on printful and get back instead `retail_price: 4400`

**Comment by ynnoj** [comment]
You can try this out on [`2.0.0-beta.1`](https://github.com/ynnoj/gatsby-source-printful/releases/tag/v2.0.0-beta.1).
