### ISSUE TITLE
Add support to pull product info?

### ISSUE THREAD

**Issue by barrymcgee** [ynnoj/gatsby-source-printful#21]
Unless I'm missing something, it's not currently possible to expose product info via this plugin?

e.g.

https://api.printful.com/products/151 will return product info for a hoodie including this description, which I need;

> A sporty hoodie with a soft inside. The iconic zip hoodie you see Silicon Valley big shots wearing - the understated yet classic look, giving off a youthful vibe.
> 
> • Flex Fleece (50% Polyester / 50% Cotton Fleece) construction
> • Metal zipper
> • Hooded with White finished Polyester drawcord
> • Kangaroo pocket
> • Unisex size – women may prefer to order one size smaller
> 
> Important: fabric of the product is prone to shrinking during wash.

I've toggled every possible option in the GraphiQL explorer but cannot return this info?

**Comment by ynnoj** [comment]
@barrymcgee As I understand it, you want to pull data for products from the Printful catalog? What is the use case?

**Comment by barrymcgee** [comment]
@ynnoj So I can show the generic description of each product for SEO among other reasons:

<img width="1331" alt="Screenshot 2020-05-29 at 14 30 19" src="https://user-images.githubusercontent.com/505570/83265177-0a2d8b00-a1b9-11ea-9922-9c4b3d8c46ff.png">

**Comment by ynnoj** [comment]
@barrymcgee Looking at the [documentation](https://www.printful.com/docs/products#getSingleSyncVariant), the Printful catalog product info is not readily available via the `/variants/:id` endpoint.

Will have to make an additional API request using the `product_id` returned.

**Comment by ynnoj** [comment]
#28 adds the catalog product and variant data to `PrintfulVariant` nodes.

```gql
{
  allPrintfulVariant {
    nodes {
      catalogVariant {
        name
      }
      catalogProduct {
        model
        description
      }
    }
  }
}
```
