### ISSUE TITLE
Populating a size dropdown box

### ISSUE THREAD

**Issue by barrymcgee** [ynnoj/gatsby-source-printful#27]
What is the recommended way to populate a dropdown box using this source method?

If I have a product in my store e.g. `123456` - when I query the `/store/products/{id}` endpoint, I am returned a list of variants, which in this case are all the different sizes of my Printful product. 

However, no-where in each variant object is the size attribute available?

Currently I have to query the name e.g. `Hoodie - S` and split the string on the dash to pull out `S` etc to populate my dropdown box.

This is obviously very brittle.. is there a way to pull this size info from the API directly?

Many thanks and thank you for the version bump with fixes earlier this week 🙌🏻

**Comment by ynnoj** [comment]
@barrymcgee This is the 'recommended' approach currently.

The sizing information for the product is stored on the Printful catalog variant related to your product/variant (if that makes sense).

By fixing #21, this data will be available on `PrintfulVariant` nodes.

**Comment by ynnoj** [comment]
#28 adds the catalog product and variant data to `PrintfulVariant` nodes. You will be able to query the size like so:

```gql
{
  allPrintfulVariant {
    nodes {
      catalogVariant {
        size
      }
    }
  }
}
```
