### ISSUE TITLE
products map is not a function

### ISSUE THREAD

**Issue by stephangriesel** [ynnoj/gatsby-source-printful#48]
I am receiving the following error when adding Printful API key to my config:

```
"gatsby-source-printful" threw an error while running the sourceNodes lifecycle:

products.map(...).flat is not a function

  63 |       variants.map(({ variant_id }) => variant_id)
  64 |     )
> 65 |     .flat()
     |      ^
  66 | 
  67 |   const uniqueCatalogVariantIds = catalogVariantIds.reduce(
  68 |     (unique, item) => (unique.includes(item) ? unique : [...unique, item]),

File: node_modules/gatsby-source-printful/gatsby-node.js:65:6
```

Here is what I have done. I am not doing any queries yet, just the basic set up:

 - Registered account on Printful, copied API key & add it in config
 - Run gatsby develop & receive error above

I can't find any documentation online how this should be configured. Any help would be appreciated.

**Comment by ynnoj** [comment]
Can you check which version of Node you're running in your environment?

**Comment by stephangriesel** [comment]
Sure thing, 10.16.3.

**Comment by ynnoj** [comment]
@stephangriesel `array.flat()` method is available from [`node@11.15.0`](https://node.green/#ES2019-features-Array-prototype--flat--flatMap--Array-prototype-flat). I'd recommend upgrading your environment to the Active LTS Node release, which is currently [12](https://nodejs.org/en/about/releases/).

I could (should) probably transpile the source with Babel to prevent this from happening.

**Comment by stephangriesel** [comment]
That seems to solve it but now I get sourceNodes lifecycle error but no detailed error message. Tried removing the package-lock file and running npm install again but not solving it.

**Comment by LuigiClaudio** [comment]
@stephangriesel did you get this latest issue you mentioned about sourceNodes lifecylces solved? I'm starting to get the following error, just started investigating.
```
error "gatsby-source-printful" threw an error while running the sourceNodes lifecycle:
warning The gatsby-source-printful plugin has generated no Gatsby nodes. Do you need it?
```

**Comment by stephangriesel** [comment]
Nope not solved @LuigiClaudio. Waiting for feedback from @ynnoj

**Comment by ynnoj** [comment]
@stephangriesel Can you please provide a functioning reproduction I can look at? I'm unable to replicate this.

**Comment by ynnoj** [comment]
Closing as this is now resolved. Tracking the other issue at #59.
