### ISSUE TITLE
"gatsby-source-printful" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by LuigiClaudio** [ynnoj/gatsby-source-printful#59]
I'm currently getting this error and no related nodes in graphql.

```
gatsby-source-printful" threw an error while running the sourceNodes lifecycle:

warning The gatsby-source-printful plugin has generated no Gatsby nodes. Do you need it?
```

I tried to go back to basics @ynnoj and instead of running my product site, I went with the `gatsby-default-starter` to avoid any possible issue with my product's set up. I did install  `gatsby-source-printful`, added it to the `gatsby-config` with a valid Printful API key and got this error , and no nodes were generated. 

These are some of the dependencies that the default starter is using today:
```
"gatsby": "^2.26.1",
"gatsby-source-filesystem": "^2.5.0",
"react": "^16.12.0",
```

I tried using both node version `12.13.0` and `14.15.0` with same results.

I see that the actual error before the warning is not really printed , it's just left blank I think.

**Comment by ynnoj** [comment]
Hey @LuigiClaudio. Can you provide me with an API key to replicate this? I'm unable to with my store keys.

Sounds like there's no products returned from the API to build nodes from.

**Comment by LuigiClaudio** [comment]
Shared the API in a DM on the twitter. 

This is the error I see that I didn't post in the previous message, my bad:

```
error Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "PrintfulCatalogVariant" does not exists'. Stacktrace was 'Error: Type with name "PrintfulCatalogVariant" does not exists
    at SchemaComposer.get (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\TypeStorage.js:44:13)
    at TypeMapper.get (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\TypeMapper.js:86:44)
    at TypeMapper.typeFromAST (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\TypeMapper.js:608:17)
    at TypeMapper.getWrapped (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\TypeMapper.js:105:17)
    at TypeMapper.convertOutputFieldConfig (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\TypeMapper.js:272:114)
    at resolveOutputConfigAsThunk (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\utils\configAsThunk.js:19:41)
    at ObjectTypeComposer.getFieldConfig (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\graphql-compose\lib\ObjectTypeComposer.js:300:58)
    at forEach (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\gatsby\src\schema\extensions\index.js:230:48)
    at Array.forEach (<anonymous>)
    at forEach (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\gatsby\src\schema\extensions\index.js:225:8)
    at Array.forEach (<anonymous>)
    at processFieldExtensions (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\gatsby\src\schema\extensions\index.js:221:32)
    at processTypeComposer (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\gatsby\src\schema\schema.js:196:11)
    at map (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\gatsby\src\schema\schema.js:170:7)
    at Array.map (<anonymous>)
    at updateSchemaComposer (D:\Files\dev\test-site-package\my-gatsby-project\node_modules\gatsby\src\schema\schema.js:169:50)'
```

**Comment by LuigiClaudio** [comment]
Quick update: think the issue is down to this and probably some inconsistency on the Printful API side, not a first :)
```
catalogVariant___NODE: variant.variant_id.toString(),
```

**Comment by ynnoj** [comment]
@LuigiClaudio I think I've tracked down the issue. Can you try out the `fix/no-corresponding-nodes-found` branch locally and let me know.

**Comment by LuigiClaudio** [comment]
@ynnoj tried the changes locally - it works with a store with one item only, but when testing with a store with more than one item, it seems to fail as before.

**Comment by ynnoj** [comment]
> @ynnoj tried the changes locally - it works with a store with one item only, but when testing with a store with more than one item, it seems to fail as before.

Strange, I've tried a few stores (with single and multiple products). Are you definitely linking to the local instance of the package in your app?

**Comment by LuigiClaudio** [comment]
> > @ynnoj tried the changes locally - it works with a store with one item only, but when testing with a store with more than one item, it seems to fail as before.
> 
> Strange, I've tried a few stores (with single and multiple products). Are you definitely linking to the local instance of the package in your app?

Yea, think so - I have set up this in the `package.json`

```
"gatsby-source-printful": "file:./gatsby-source-printful-fix-no-corresponding-nodes-found/gatsby-source-printful",
```

and when checking in the modules installed I see the version of the `gatsby-node.js` file with the changes I saw in the diffs. The store that fails for me has 35 items. I've added a second item to the store I shared with you and it works, so two items are fine as well as just one. How many items in the store with multiples items do you have?

**Comment by ynnoj** [comment]
It's easier to just do [`yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/). The number of products shouldn't really impact this.

**Comment by ynnoj** [comment]
After some debugging, the issue is that the source plugin is being rate limited by the Printful API. They have a limit of 120 requests per minute so some stores will be exceeding this, especially since the addition of [Printful catalog data](https://github.com/ynnoj/gatsby-source-printful/pull/28) to the library. There's a `fetch` error (`429`) during the `sourceNodes` lifecycle which results in no nodes being built.

This raises a couple of concerns/problems:

1. Better error handling. The `429` error in this case isn't surfaced during the `sourceNodes` lifecycle. The build should ideally surface all errors to the user, and in some cases panic.
2. We need to factor in the rate limiting. Gatsby's GraphQL interface means source plugins fire a ton of network requests over a short period of time. This is an issue when working with public APIs as they often have rate limiting in place. We might need to implement some retry methods to counter this.

In the meantime, there's a couple improvements we can make that should help reduce the number of network requests and bring the library unto the API rate limit for _most stores_.

1. Rather than making an API request for each individual catalog variant, request the catalog product. Catalog variants are included in the catalog product payload. This would help reduce API requests significantly.

    * For example, a store with 10 products each using a unique Printful catalog product with 4 size/colour variations would currently result in **40** API requests. This could be refactored to reduce to just **10**.

2. Allow for the generation of Printful catalog nodes to be optional. A configuration option could be added to prevent Painful catalog data being fetched as in some cases this data isn't used.

**Comment by ynnoj** [comment]
@LuigiClaudio Tested refactoring API calls for catalog data with the store you've had issues with and it's building fine now.

* Current approach (1x API request for each unique catalog variant): **116** requests.
* Proposed refactor (1x API request for each unique catalog product): **17** requests.

**Comment by LuigiClaudio** [comment]
> @LuigiClaudio Tested refactoring API calls for catalog data with the store you've had issues with and it's building fine now.
> 
> * Current approach (1x API request for each unique catalog variant): **116** requests.
> * Proposed refactor (1x API request for each unique catalog product): **17** requests.

Sounds great! Let me know if I can do anything to test or help somehow.

**Comment by ynnoj** [comment]
Try out the branch on #61.

**Comment by LuigiClaudio** [comment]
Looks good. It builds. 👏🎉
