### ISSUE TITLE
add limit to 100

### ISSUE THREAD

**Issue by svengau** [ynnoj/gatsby-source-printful#7]
Hello, 
by default, the limit is 20 for all lists. Please, could you add a limit to 100 ?

example: /sync/products?limit=100 

Thanks

**Comment by ynnoj** [comment]
@svengau Hey! Thanks for the suggestion.

Would a better solution here be to paginate requests to Printful?

**Comment by svengau** [comment]
Hey @ynnoj, but I was proposing a quick solution, but yes indeed, paginate requests are a betteer solution.

**Comment by ynnoj** [comment]
@svengau Just opened #11 to add pagination. Let me know your thoughts.

**Comment by svengau** [comment]
thanks @ynnoj
