### ISSUE TITLE
Cannot read property 'preview_url' of undefined

### ISSUE THREAD

**Issue by LuigiClaudio** [ynnoj/gatsby-source-printful#8]
I'm able to see the nodes in graphql, I'm hitting this error in the terminal when building 

```
gatsby-source-printful: TypeError: Cannot read property 'preview_url' of undefined
@ gatsby-node.js line:77 
```

it looks it has to do with the preview image, what would you suggest to look at?

I see few of the these `product: null` in the query before the actual products that returns the expected object:

```
"allPrintfulVariant": {
      "nodes": [
        {
          "product": null
        },
```

**Comment by LuigiClaudio** [comment]
It seems down to creating nodes of _Not synced_ products that I see I have in the store, and for these _Not synced_ products I have no printful product associated with it hence the `null` product I get in the query mentioned in the comment above. I guess that removing these variants would solve the error.
![image](https://user-images.githubusercontent.com/369943/81854276-ff8ab900-955d-11ea-9d3d-150181c75dda.png)

**Comment by ynnoj** [comment]
Problem likely stems from the variant having no images, and therefore `previewFile` is undefined.

https://github.com/ynnoj/gatsby-source-printful/blob/2d00578286ac5ad0ebc9b09507f912c6a0d71556/gatsby-source-printful/gatsby-node.js#L112
