### ISSUE TITLE
Support for Printful new Developer API access token

### ISSUE THREAD

**Issue by raqibjs** [ynnoj/gatsby-source-printful#81]
**Printful will stop support for API key in the next year.** They already announced API key as **legacy**. Now they want us to use their Developer API for external integration. So we need a way to provide an **access token** with the source plugin.

**Migration guide** - https://help.printful.com/hc/en-us/articles/4632388335260-What-should-I-know-about-API-key-to-API-token-migration

![image](https://user-images.githubusercontent.com/11327451/194080301-67c8e33f-a5e5-4578-a628-8bed68327bec.png)

@notrab @svengau @ynnoj @renovate-bot

**Comment by notrab** [comment]
@raqibjs this #82 should do it!
