### ISSUE TITLE
UNHANDLED REJECTION Encountered an error trying to infer a GraphQL type for: `variants___NODE`.

### ISSUE THREAD

**Issue by LuigiClaudio** [ynnoj/gatsby-source-printful#9]
Hitting this error when Gatsby builds the schema and with only one product in the store.

`UNHANDLED REJECTION Encountered an error trying to infer a GraphQL type for: `variants___NODE`. There is no corresponding node with the `id` field matching: "5ebd6716225212,5ebd6716225278,5ebd67162252d2,5ebd6716225329,5ebd6716225379,5ebd67162253c8,5ebd6716225412,5ebd6716225465,5ebd67162254b1".`

**Comment by LuigiClaudio** [comment]
Adding a second item solves the issue.

**Comment by ynnoj** [comment]
@LuigiClaudio Can you provide a replication? I can't replicate this, may have just been a Gatsby cache thing.

**Comment by ynnoj** [comment]
Going to close this. Please re-open if this persists.

**Comment by LuigiClaudio** [comment]
sure, sorry my bad. Hadn't had a chance to test it but I'll let you know if I see it and will keep an eye on the cache that you suggested.

**Comment by affluent-bilby-classifieds** [comment]
I got a very similar error:

Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `catalogVariant___NODE`. There is no corresp  onding node with the `id` field matching: "68,130,192,254,316,378,440,1037,1051,1065,1079,1093,1320,4830".

**Comment by ludusrusso** [comment]
Hi, I've got similar errors and it seems related to caching. It appears when I add new item on the store and I can solve it by clean cache! Any solution to solve it without removing cache?

**Comment by NatixDev** [comment]
Same question as ludusrusso.

**Comment by ynnoj** [comment]
@affluent-bilby-classifieds @ludusrusso @NatixDev Can you try out the branch on #60? This should hopefully resolve this issue.
